version: '3.8'
services:
  app:
    image: go-fiber:latest
    env_file:
      - .env
    ports:
      - 9000:${FIBER_PORT}
    volumes:
      - .:/usr/src/some-api
    command: air cmd/main.go -b 0.0.0.0
    depends_on:
      - postgres
    networks:
      - fiber
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - fiber

volumes:
  postgres-db:

networks:
  fiber:
    driver: bridge